package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CartHasProduct generated by hbm2java
 */
public class CartHasProduct  implements java.io.Serializable {


     private Integer id;
     private Cart cart;
     private Product product;
     private double qty;
     private Date dateAdd;
     private String shippingAddressType;
     private Date dateDiliver;
     private Date dateShipped;
     private Date datePurchased;
     private String total;
     private int status;
     private Set checkouts = new HashSet(0);
     private Set shippingdetailses = new HashSet(0);

    public CartHasProduct() {
    }

	
    public CartHasProduct(Cart cart, Product product, double qty, Date dateAdd, String shippingAddressType, int status) {
        this.cart = cart;
        this.product = product;
        this.qty = qty;
        this.dateAdd = dateAdd;
        this.shippingAddressType = shippingAddressType;
        this.status = status;
    }
    public CartHasProduct(Cart cart, Product product, double qty, Date dateAdd, String shippingAddressType, Date dateDiliver, Date dateShipped, Date datePurchased, String total, int status, Set checkouts, Set shippingdetailses) {
       this.cart = cart;
       this.product = product;
       this.qty = qty;
       this.dateAdd = dateAdd;
       this.shippingAddressType = shippingAddressType;
       this.dateDiliver = dateDiliver;
       this.dateShipped = dateShipped;
       this.datePurchased = datePurchased;
       this.total = total;
       this.status = status;
       this.checkouts = checkouts;
       this.shippingdetailses = shippingdetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public double getQty() {
        return this.qty;
    }
    
    public void setQty(double qty) {
        this.qty = qty;
    }
    public Date getDateAdd() {
        return this.dateAdd;
    }
    
    public void setDateAdd(Date dateAdd) {
        this.dateAdd = dateAdd;
    }
    public String getShippingAddressType() {
        return this.shippingAddressType;
    }
    
    public void setShippingAddressType(String shippingAddressType) {
        this.shippingAddressType = shippingAddressType;
    }
    public Date getDateDiliver() {
        return this.dateDiliver;
    }
    
    public void setDateDiliver(Date dateDiliver) {
        this.dateDiliver = dateDiliver;
    }
    public Date getDateShipped() {
        return this.dateShipped;
    }
    
    public void setDateShipped(Date dateShipped) {
        this.dateShipped = dateShipped;
    }
    public Date getDatePurchased() {
        return this.datePurchased;
    }
    
    public void setDatePurchased(Date datePurchased) {
        this.datePurchased = datePurchased;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }
    public Set getShippingdetailses() {
        return this.shippingdetailses;
    }
    
    public void setShippingdetailses(Set shippingdetailses) {
        this.shippingdetailses = shippingdetailses;
    }




}


