package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idCart;
     private UserReg userReg;
     private Integer totalProduct;
     private Double totalAmout;
     private String shippingAddress;
     private Set cartHasProducts = new HashSet(0);

    public Cart() {
    }

	
    public Cart(UserReg userReg) {
        this.userReg = userReg;
    }
    public Cart(UserReg userReg, Integer totalProduct, Double totalAmout, String shippingAddress, Set cartHasProducts) {
       this.userReg = userReg;
       this.totalProduct = totalProduct;
       this.totalAmout = totalAmout;
       this.shippingAddress = shippingAddress;
       this.cartHasProducts = cartHasProducts;
    }
   
    public Integer getIdCart() {
        return this.idCart;
    }
    
    public void setIdCart(Integer idCart) {
        this.idCart = idCart;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public Integer getTotalProduct() {
        return this.totalProduct;
    }
    
    public void setTotalProduct(Integer totalProduct) {
        this.totalProduct = totalProduct;
    }
    public Double getTotalAmout() {
        return this.totalAmout;
    }
    
    public void setTotalAmout(Double totalAmout) {
        this.totalAmout = totalAmout;
    }
    public String getShippingAddress() {
        return this.shippingAddress;
    }
    
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }
    public Set getCartHasProducts() {
        return this.cartHasProducts;
    }
    
    public void setCartHasProducts(Set cartHasProducts) {
        this.cartHasProducts = cartHasProducts;
    }




}


