package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private Integer idCheckout;
     private CartHasProduct cartHasProduct;
     private Date date;

    public Checkout() {
    }

    public Checkout(CartHasProduct cartHasProduct, Date date) {
       this.cartHasProduct = cartHasProduct;
       this.date = date;
    }
   
    public Integer getIdCheckout() {
        return this.idCheckout;
    }
    
    public void setIdCheckout(Integer idCheckout) {
        this.idCheckout = idCheckout;
    }
    public CartHasProduct getCartHasProduct() {
        return this.cartHasProduct;
    }
    
    public void setCartHasProduct(CartHasProduct cartHasProduct) {
        this.cartHasProduct = cartHasProduct;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


