package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA



/**
 * DileverCharge generated by hbm2java
 */
public class DileverCharge  implements java.io.Serializable {


     private Integer did;
     private String district;
     private String charge;

    public DileverCharge() {
    }

    public DileverCharge(String district, String charge) {
       this.district = district;
       this.charge = charge;
    }
   
    public Integer getDid() {
        return this.did;
    }
    
    public void setDid(Integer did) {
        this.did = did;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCharge() {
        return this.charge;
    }
    
    public void setCharge(String charge) {
        this.charge = charge;
    }




}


