package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer idlog;
     private UserReg userReg;
     private Date date;
     private String userRole;
     private Date time;

    public Log() {
    }

	
    public Log(UserReg userReg, Date date) {
        this.userReg = userReg;
        this.date = date;
    }
    public Log(UserReg userReg, Date date, String userRole, Date time) {
       this.userReg = userReg;
       this.date = date;
       this.userRole = userRole;
       this.time = time;
    }
   
    public Integer getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(Integer idlog) {
        this.idlog = idlog;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


