package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private Integer idmodel;
     private ProductBrand productBrand;
     private String modelName;
     private String status;
     private Set volumes = new HashSet(0);
     private Set products = new HashSet(0);

    public Model() {
    }

	
    public Model(ProductBrand productBrand, String modelName) {
        this.productBrand = productBrand;
        this.modelName = modelName;
    }
    public Model(ProductBrand productBrand, String modelName, String status, Set volumes, Set products) {
       this.productBrand = productBrand;
       this.modelName = modelName;
       this.status = status;
       this.volumes = volumes;
       this.products = products;
    }
   
    public Integer getIdmodel() {
        return this.idmodel;
    }
    
    public void setIdmodel(Integer idmodel) {
        this.idmodel = idmodel;
    }
    public ProductBrand getProductBrand() {
        return this.productBrand;
    }
    
    public void setProductBrand(ProductBrand productBrand) {
        this.productBrand = productBrand;
    }
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getVolumes() {
        return this.volumes;
    }
    
    public void setVolumes(Set volumes) {
        this.volumes = volumes;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


