package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Privelage generated by hbm2java
 */
public class Privelage  implements java.io.Serializable {


     private Integer idPrivelage;
     private String page;
     private String capabilt;
     private Set userTypeHasPrivelages = new HashSet(0);

    public Privelage() {
    }

    public Privelage(String page, String capabilt, Set userTypeHasPrivelages) {
       this.page = page;
       this.capabilt = capabilt;
       this.userTypeHasPrivelages = userTypeHasPrivelages;
    }
   
    public Integer getIdPrivelage() {
        return this.idPrivelage;
    }
    
    public void setIdPrivelage(Integer idPrivelage) {
        this.idPrivelage = idPrivelage;
    }
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }
    public String getCapabilt() {
        return this.capabilt;
    }
    
    public void setCapabilt(String capabilt) {
        this.capabilt = capabilt;
    }
    public Set getUserTypeHasPrivelages() {
        return this.userTypeHasPrivelages;
    }
    
    public void setUserTypeHasPrivelages(Set userTypeHasPrivelages) {
        this.userTypeHasPrivelages = userTypeHasPrivelages;
    }




}


