package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProductBrand generated by hbm2java
 */
public class ProductBrand  implements java.io.Serializable {


     private Integer idBrand;
     private String BName;
     private String status;
     private Set products = new HashSet(0);
     private Set models = new HashSet(0);

    public ProductBrand() {
    }

    public ProductBrand(String BName, String status, Set products, Set models) {
       this.BName = BName;
       this.status = status;
       this.products = products;
       this.models = models;
    }
   
    public Integer getIdBrand() {
        return this.idBrand;
    }
    
    public void setIdBrand(Integer idBrand) {
        this.idBrand = idBrand;
    }
    public String getBName() {
        return this.BName;
    }
    
    public void setBName(String BName) {
        this.BName = BName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }
    public Set getModels() {
        return this.models;
    }
    
    public void setModels(Set models) {
        this.models = models;
    }




}


