package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idProduct;
     private Model model;
     private ProductType productType;
     private ProductBrand productBrand;
     private Volume volume;
     private String name;
     private String qty;
     private String price;
     private String image1;
     private String image2;
     private String image3;
     private String discount;
     private String details;
     private String status;
     private Set wishLists = new HashSet(0);
     private Set cartHasProducts = new HashSet(0);
     private Set stockIns = new HashSet(0);

    public Product() {
    }

	
    public Product(Model model, ProductType productType, ProductBrand productBrand, String details) {
        this.model = model;
        this.productType = productType;
        this.productBrand = productBrand;
        this.details = details;
    }
    public Product(Model model, ProductType productType, ProductBrand productBrand, Volume volume, String name, String qty, String price, String image1, String image2, String image3, String discount, String details, String status, Set wishLists, Set cartHasProducts, Set stockIns) {
       this.model = model;
       this.productType = productType;
       this.productBrand = productBrand;
       this.volume = volume;
       this.name = name;
       this.qty = qty;
       this.price = price;
       this.image1 = image1;
       this.image2 = image2;
       this.image3 = image3;
       this.discount = discount;
       this.details = details;
       this.status = status;
       this.wishLists = wishLists;
       this.cartHasProducts = cartHasProducts;
       this.stockIns = stockIns;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }
    public ProductBrand getProductBrand() {
        return this.productBrand;
    }
    
    public void setProductBrand(ProductBrand productBrand) {
        this.productBrand = productBrand;
    }
    public Volume getVolume() {
        return this.volume;
    }
    
    public void setVolume(Volume volume) {
        this.volume = volume;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getImage1() {
        return this.image1;
    }
    
    public void setImage1(String image1) {
        this.image1 = image1;
    }
    public String getImage2() {
        return this.image2;
    }
    
    public void setImage2(String image2) {
        this.image2 = image2;
    }
    public String getImage3() {
        return this.image3;
    }
    
    public void setImage3(String image3) {
        this.image3 = image3;
    }
    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }
    public Set getCartHasProducts() {
        return this.cartHasProducts;
    }
    
    public void setCartHasProducts(Set cartHasProducts) {
        this.cartHasProducts = cartHasProducts;
    }
    public Set getStockIns() {
        return this.stockIns;
    }
    
    public void setStockIns(Set stockIns) {
        this.stockIns = stockIns;
    }




}


