package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable {


     private Integer idType;
     private String typeName;
     private String status;
     private Set products = new HashSet(0);

    public ProductType() {
    }

    public ProductType(String typeName, String status, Set products) {
       this.typeName = typeName;
       this.status = status;
       this.products = products;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


