package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Shippingdetails generated by hbm2java
 */
public class Shippingdetails  implements java.io.Serializable {


     private Integer idshippingDetails;
     private CartHasProduct cartHasProduct;
     private String address1;
     private String address2;
     private String address3;
     private String city;
     private String province;
     private String country;

    public Shippingdetails() {
    }

	
    public Shippingdetails(CartHasProduct cartHasProduct) {
        this.cartHasProduct = cartHasProduct;
    }
    public Shippingdetails(CartHasProduct cartHasProduct, String address1, String address2, String address3, String city, String province, String country) {
       this.cartHasProduct = cartHasProduct;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.city = city;
       this.province = province;
       this.country = country;
    }
   
    public Integer getIdshippingDetails() {
        return this.idshippingDetails;
    }
    
    public void setIdshippingDetails(Integer idshippingDetails) {
        this.idshippingDetails = idshippingDetails;
    }
    public CartHasProduct getCartHasProduct() {
        return this.cartHasProduct;
    }
    
    public void setCartHasProduct(CartHasProduct cartHasProduct) {
        this.cartHasProduct = cartHasProduct;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


