package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA



/**
 * StockIn generated by hbm2java
 */
public class StockIn  implements java.io.Serializable {


     private Integer idStock;
     private Product product;
     private String addDate;
     private String qty;

    public StockIn() {
    }

	
    public StockIn(Product product) {
        this.product = product;
    }
    public StockIn(Product product, String addDate, String qty) {
       this.product = product;
       this.addDate = addDate;
       this.qty = qty;
    }
   
    public Integer getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(Integer idStock) {
        this.idStock = idStock;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(String addDate) {
        this.addDate = addDate;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }




}


