package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA



/**
 * UserTypeHasPrivelage generated by hbm2java
 */
public class UserTypeHasPrivelage  implements java.io.Serializable {


     private Integer id;
     private UserType userType;
     private Privelage privelage;
     private String status;

    public UserTypeHasPrivelage() {
    }

	
    public UserTypeHasPrivelage(UserType userType, Privelage privelage) {
        this.userType = userType;
        this.privelage = privelage;
    }
    public UserTypeHasPrivelage(UserType userType, Privelage privelage, String status) {
       this.userType = userType;
       this.privelage = privelage;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public Privelage getPrivelage() {
        return this.privelage;
    }
    
    public void setPrivelage(Privelage privelage) {
        this.privelage = privelage;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


