package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserReg generated by hbm2java
 */
public class UserReg  implements java.io.Serializable {


     private Integer idUserReg;
     private UserType userType;
     private String FName;
     private String LName;
     private String email;
     private String address1;
     private String address2;
     private String address3;
     private String uname;
     private String gender;
     private String password1;
     private String password2;
     private String status;
     private Set siteChanges = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set wishLists = new HashSet(0);
     private Set carts = new HashSet(0);

    public UserReg() {
    }

	
    public UserReg(UserType userType) {
        this.userType = userType;
    }
    public UserReg(UserType userType, String FName, String LName, String email, String address1, String address2, String address3, String uname, String gender, String password1, String password2, String status, Set siteChanges, Set logs, Set wishLists, Set carts) {
       this.userType = userType;
       this.FName = FName;
       this.LName = LName;
       this.email = email;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.uname = uname;
       this.gender = gender;
       this.password1 = password1;
       this.password2 = password2;
       this.status = status;
       this.siteChanges = siteChanges;
       this.logs = logs;
       this.wishLists = wishLists;
       this.carts = carts;
    }
   
    public Integer getIdUserReg() {
        return this.idUserReg;
    }
    
    public void setIdUserReg(Integer idUserReg) {
        this.idUserReg = idUserReg;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPassword1() {
        return this.password1;
    }
    
    public void setPassword1(String password1) {
        this.password1 = password1;
    }
    public String getPassword2() {
        return this.password2;
    }
    
    public void setPassword2(String password2) {
        this.password2 = password2;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getSiteChanges() {
        return this.siteChanges;
    }
    
    public void setSiteChanges(Set siteChanges) {
        this.siteChanges = siteChanges;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


