package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer idUserType;
     private String type;
     private Set userRegs = new HashSet(0);
     private Set userTypeHasPrivelages = new HashSet(0);

    public UserType() {
    }

    public UserType(String type, Set userRegs, Set userTypeHasPrivelages) {
       this.type = type;
       this.userRegs = userRegs;
       this.userTypeHasPrivelages = userTypeHasPrivelages;
    }
   
    public Integer getIdUserType() {
        return this.idUserType;
    }
    
    public void setIdUserType(Integer idUserType) {
        this.idUserType = idUserType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getUserRegs() {
        return this.userRegs;
    }
    
    public void setUserRegs(Set userRegs) {
        this.userRegs = userRegs;
    }
    public Set getUserTypeHasPrivelages() {
        return this.userTypeHasPrivelages;
    }
    
    public void setUserTypeHasPrivelages(Set userTypeHasPrivelages) {
        this.userTypeHasPrivelages = userTypeHasPrivelages;
    }




}


