package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Volume generated by hbm2java
 */
public class Volume  implements java.io.Serializable {


     private Integer idvolume;
     private Model model;
     private String vol;
     private String status;
     private Set products = new HashSet(0);

    public Volume() {
    }

	
    public Volume(Model model, String vol) {
        this.model = model;
        this.vol = vol;
    }
    public Volume(Model model, String vol, String status, Set products) {
       this.model = model;
       this.vol = vol;
       this.status = status;
       this.products = products;
    }
   
    public Integer getIdvolume() {
        return this.idvolume;
    }
    
    public void setIdvolume(Integer idvolume) {
        this.idvolume = idvolume;
    }
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    public String getVol() {
        return this.vol;
    }
    
    public void setVol(String vol) {
        this.vol = vol;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


