package pojo;
// Generated Feb 14, 2016 8:17:19 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WishList generated by hbm2java
 */
public class WishList  implements java.io.Serializable {


     private int idWishList;
     private UserReg userReg;
     private Product product;
     private Date date;

    public WishList() {
    }

    public WishList(int idWishList, UserReg userReg, Product product, Date date) {
       this.idWishList = idWishList;
       this.userReg = userReg;
       this.product = product;
       this.date = date;
    }
   
    public int getIdWishList() {
        return this.idWishList;
    }
    
    public void setIdWishList(int idWishList) {
        this.idWishList = idWishList;
    }
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg userReg) {
        this.userReg = userReg;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


